# Generated by Django 3.1.5 on 2021-01-14 03:37

from django.db import migrations

def create_data(apps,schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(first_name="Customer 001", last_name="Customer 001", email="cutomer001@email.com",
             phone="00000000", address="Customer 000 Address", description="Customer 001 Description").save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
